### ISSUE TITLE
Function visibility level

### ISSUE THREAD

**Issue by Maxxxell** [WojcikMM/eth-angular-voting-dapp#1]
I really like your repo, 
so I noticed that the function getCampaignInfo(address senderAddress) in Campaign.sol should be public.

**Comment by WojcikMM** [comment]
Thanks a lot. Yes you are right. Previously, this function was only called by CampaignFactory.sol, but now it's also called internally, so it should be public. I'll fix it immediately.

**Comment by WojcikMM** [comment]
Fixed in #2
